spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  error:
    include-message: always
